version: 2.1

workflows:
  test-deploy-two-jobs:
    jobs:
      - settings
      - build:
        requires:
          - settings

jobs:
  settings:
    docker:
      - image: cimg/php:8.2.6
    steps:
      - checkout
      - run: php --version
  build:
    docker:
      - image: cimg/php:8.2.6
    steps:
      - run: composer install
      - run: php artisan optimize:clear
      - run: php artisan test
