version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/php:8.2.6
    steps:
      - checkout
      - run: php --version
      - run: composer install
      - run: php artisan optimize:clear
      - run: php artisan test
